# nonk8s
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    uid: lokidatasource
    jsonData:
      timeout: 60
      maxLines: 2000

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheusdatasource
    jsonData:
      timeout: 60