name: spring-boot-microservices

services:
  users-ms:
    image: vromanyu/users-ms
    container_name: users-ms
    hostname: users-ms
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    networks:
      microservices-network:

  banking-app-ms:
      image: vromanyu/banking-app-ms
      container_name: banking-app-ms
      hostname: banking-app-ms
      depends_on:
        postgresql:
          condition: service_healthy
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ports:
        - "8082:8082"
      networks:
        microservices-network:

  employee-management-ms:
    image: vromanyu/employee-management-ms
    container_name: employee-management-ms
    hostname: employee-management-ms
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8083:8083"
    networks:
      microservices-network:

  postgresql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      test: pg_isready
      interval: 1s
      start_period: 2s
      retries: 3
    networks:
      microservices-network:

networks:
  microservices-network:
    driver: bridge
