name: spring-boot-microservices

services:

  config-server:
    image: vromanyu/config-server:jdk-25
    container_name: config-server
    hostname: config-server
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      microservices-network:

  ms-registry:
    image: vromanyu/ms-registry:jdk-25
    container_name: ms-registry
    hostname: ms-registry
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER: "config-server"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      microservices-network:

  api-gateway:
    image: vromanyu/api-gateway:jdk-25
    container_name: api-gateway
    hostname: api-gateway
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      REDIS_HOST: "redis"
    ports:
      - "8585:8585"
    depends_on:
      ms-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8585/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      microservices-network:

  department-ms:
    image: vromanyu/department-ms:jdk-25
    container_name: department-ms
    hostname: department-ms
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: "postgres"
    depends_on:
      ms-registry:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8182/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      microservices-network:

  employee-ms:
    image: vromanyu/employee-ms:jdk-25
    container_name: employee-ms
    hostname: employee-ms
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: "postgres"
    depends_on:
      ms-registry:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8183/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      microservices-network:

  postgresql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 1s
      start_period: 2s
      retries: 3
    networks:
      microservices-network:

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      microservices-network:

networks:
  microservices-network:
    driver: bridge
