name: spring-boot-microservices

services:

  config-server:
    image: vromanyu/config-server:jdk-25
    container_name: config-server
    hostname: config-server
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: config-server
    networks:
      - microservices-network

  ms-registry:
    image: vromanyu/ms-registry:jdk-25
    container_name: ms-registry
    hostname: ms-registry
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER: "config-server"
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: ms-registry
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - microservices-network

  api-gateway:
    image: vromanyu/api-gateway:jdk-25
    container_name: api-gateway
    hostname: api-gateway
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      REDIS_HOST: "redis"
      KEYCLOAK_HOST: "keycloak"
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: api-gateway
    ports:
      - "8585:8585"
    depends_on:
      ms-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8585/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - microservices-network

  department-ms:
    image: vromanyu/department-ms:jdk-25
    container_name: department-ms
    hostname: department-ms
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: "postgres"
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: department-ms
    depends_on:
      ms-registry:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8182/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - microservices-network

  employee-ms:
    image: vromanyu/employee-ms:jdk-25
    container_name: employee-ms
    hostname: employee-ms
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: "postgres"
      RABBITMQ_HOST: "rabbitmq"
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: employee-ms
    depends_on:
      ms-registry:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8183/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - microservices-network

  message-ms:
    image: vromanyu/message-ms:jdk-25
    container_name: message-ms
    hostname: message-ms
    environment:
      CONFIG_SERVER: "config-server"
      MS_REGISTRY: "ms-registry"
      RABBITMQ_HOST: "rabbitmq"
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_DEFAULT_ENCODING: ${MAIL_DEFAULT_ENCODING}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JAVA_TOOL_OPTIONS: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: message-ms
    env_file:
      - .env
    healthcheck:
      test: "curl --fail --silent localhost:9010/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      ms-registry:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    networks:
      - microservices-network

  postgresql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 1s
      start_period: 2s
      retries: 3
    networks:
      - microservices-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - microservices-network

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    hostname: loki
    volumes:
      - ./loki:/mnt/config
    ports:
      - "3100:3100"
    command:
      - "-config.file=/mnt/config/loki-config.yaml"
    networks:
      - microservices-network

  tempo:
    image: grafana/tempo
    container_name: tempo
    hostname: tempo
    ports:
      - "3110:3200"
      - "4318:4318"
      - "4317:4317"
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml
    networks:
      - microservices-network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    env_file:
      - .env
    networks:
      - microservices-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: keycloak
    hostname: keycloak
    ports:
      - "7080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - microservices-network

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    hostname: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PG_USER: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - microservices-network

  rabbit:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
      - "15672:15672"
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge
