name: config-server-workflow
on:
  push:
    branches:
      - main
    paths:
      - config-server/**
  pull_request:
    branches:
      - main
    paths:
      - config-server/**
  workflow_dispatch:

jobs:
  config-server-ci:
    strategy:
      matrix:
        java-version: [21, 25]
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build/Test
        id: build
        run: mvn -B package --file ./config-server/pom.xml -Djava.version=${{matrix.java-version}}
      - name: Upload Artifact
        if: success() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{matrix.java-version}}
          path: ./config-server/target/*.jar
