name: springboot-restful-webservices-ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".idea/**"
      - "pom.xml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".idea/**"
      - "pom.xml"
  workflow_dispatch:


jobs:
  springboot-restful-webservices-ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    env:
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Build/Test
        id: build
        run: mvn -B package --file ./springboot-restful-webservices/pom.xml
      - name: Upload Artifact
        if: success() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./springboot-restful-webservices/target/*.jar
